version: 2

updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "05:00"
      timezone: Europe/Berlin
    open-pull-requests-limit: 10
    labels:
      - dependencies
      - npm
    commit-message:
      prefix: chore
      include: scope
    groups:
      docusaurus:
        patterns:
          - "@docusaurus/*"
          - "docusaurus"
      npm-non-major:
        dependency-type: production
        update-types:
          - minor
          - patch
        exclude-patterns:
          - "@docusaurus/*"
          - "docusaurus"
      npm-dev-non-major:
        dependency-type: development
        update-types:
          - minor
          - patch
        exclude-patterns:
          - "@docusaurus/*"
          - "docusaurus"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "05:30"
      timezone: Europe/Berlin
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - github-actions
    commit-message:
      prefix: chore
      include: scope
    groups:
      github-actions-non-major:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
